### ISSUE TITLE
TypeError after setting ElectrodeMode

### ISSUE THREAD

**Issue by StevenSchamber** [OpenEIT/OpenEIT#41]
I get this following TypeError every time starting the software.

`32 electrode mode
baselining
2020-09-10 12:13:52,892 reconstruction time: 0.00
2020-09-10 12:13:52,962 Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1059, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 994, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "C:\Users\OpenEIT-master\OpenEIT\dashboard\modes\imaging.py", line 445, in display_controls
    therange = int(datasource_2_value) - int(datasource_1_value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'`

Although this error im able to see datastream and imaging is also working

**Comment by JeanRintoul** [comment]
I've tried recreating this in both OSX and Windows and haven't been able to. I get no errors. What version of dash are you using? Do you have a detailed set of instructions as to how to recreate this error?
