### ISSUE TITLE
KeyError after setting autoscale 

### ISSUE THREAD

**Issue by StevenSchamber** [OpenEIT/OpenEIT#42]
I get this Error after setting autoscale. Although imaging is working 

`we are in the autoscale function
we are in the autoscale function
2020-09-10 12:23:06,183 Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1059, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 994, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "C:\Users\OpenEIT-master\OpenEIT\dashboard\modes\imaging.py", line 418, in autoscale_data
    autoscale()
  File "C:\Users\OpenEIT-master\OpenEIT\dashboard\modes\imaging.py", line 642, in autoscale
    display_controls(self.vmin,self.vmax)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 991, in add_context
    output_spec = kwargs.pop("outputs_list")
KeyError: 'outputs_list'
2020-09-10 12:23:06,183 Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 1059, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 994, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "C:\Users\OpenEIT-master\OpenEIT\dashboard\modes\imaging.py", line 410, in autoscale_data
    autoscale()
  File "C:\Users\OpenEIT-master\OpenEIT\dashboard\modes\imaging.py", line 642, in autoscale
    display_controls(self.vmin,self.vmax)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dash\dash.py", line 991, in add_context
    output_spec = kwargs.pop("outputs_list")
KeyError: 'outputs_list'`

**Comment by JeanRintoul** [comment]
I've tried recreating this in both OSX and Windows and haven't been able to. I'd need some more information to further diagnose. What version of dash are you using?
